server:
  port: ${USER_PORT}

spring:
  profiles:
    active: "default"
  application:
    name: "user-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: "${MYSQLDB}"
    password: "${MYSQLDB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DATABASE_NAME}:${DBPORT}/${DBNAME}"
    initialization-mode: always

app:
  admin-portal: "${PORTAL_ADMIN}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  landing-portal: "${PORTAL_LANDING}"
  sms:
    enable: true
  email:
    from: "no-reply@alinefinancial.com"
    enable: true
  security:
    secret-key: ${SECRET_KEY}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
  aws:
    email:
      template-bucket-name: "aline-email-templates"
    credentials:
      access-key-id: "${APP_USER_ACCESS_KEY}"
      secret-access-key: "${APP_USER_SECRET_KEY}"
